name: pro_lints
description: Lints for Dart and Flutter projects.

repository: https://github.com/pro100andrey/pro_lints
issue_tracker: https://github.com/pro100andrey/pro_lints/issues
homepage: https://github.com/pro100andrey/pro_lints
documentation: https://github.com/pro100andrey/pro_lints/blob/main/README.md

version: 6.1.0

environment:
  sdk: ^3.11.5

topics:
  - lints
  - analysis

